# Generated by Django 5.0.1 on 2026-02-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("product_manager", "Product Manager"),
                            ("ui_ux_designer", "UI/UX Designer"),
                            ("frontend_developer", "Frontend Developer"),
                            ("backend_developer", "Backend Developer"),
                            ("qa_engineer", "QA Engineer"),
                            ("devops_engineer", "DevOps Engineer"),
                            ("data_analyst", "Data Analyst"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("design", "Design"),
                            ("marketing", "Marketing"),
                            ("sales", "Sales"),
                            ("hr", "Human Resources"),
                            ("finance", "Finance"),
                            ("support", "Customer Support"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("working", "Working"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("avatar", models.CharField(default="🤖", max_length=10)),
                ("skills", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["department", "name"],
            },
        ),
    ]
