# Generated by Django 5.0.1 on 2026-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubaccount",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
